5/frontend poc
Antranduc/weightao pull request #8
Opened 2021-03-26 00:10 UTC by Weitaozhang123

Frontend implementation

2021-04-05 17:21 UTC, Shey99 requested changes

2021-04-06 00:27 UTC, Weitaozhang123 commented on weightao/Exercise.swift
> +        }
I just used the ? in a function to clean up the code which should make it more dry.

2021-04-06 00:32 UTC, Weitaozhang123 commented on weightao/Exercise.swift
> +    private var weightType: Bool
Done got rid of the lbkg field and just used weightType directly. I might implement throwing an exception if the user inputs something that isn't pounds or kgs.

2021-04-06 00:33 UTC, Weitaozhang123 commented on weightao/Exercise.swift
> +        }
Got rid of the lbkg field and using weightType as a string now.

2021-04-06 00:59 UTC, Shey99 commented on weightao/Exercise.swift
> +    private var weightType: Bool
Error handling is good thinking but we might just be able to make the user enter this via a dropdown instead of a text field so they don't have the option of entering anything else like so https://miro.medium.com/max/1720/1*LJujvSAe2lGVdY2ETmg5ew.png

2021-04-06 01:14 UTC, Weitaozhang123 commented on weightao/HomepageView.swift
> +                DisclosureGroup("                           Week \(weekSelected)", isExpanded: $isExpanded) {
I'm not finding any resources online about how to tackle this. I might need to open a new issue just to work on this. I think one way to tackle this is to create a custom drop down menu instead of using disclosure group.

2021-04-06 01:15 UTC, Weitaozhang123 commented on weightao/Exercise.swift
> +    private var weightType: Bool
That sounds like a great idea, I think that will work well.

2021-06-13 18:54 UTC, Shey99 approved these changes

2021-06-13 18:55 UTC, merged